---
language: java
jdk:
- oraclejdk7
- openjdk7
env:
  global:
  - PLAY_VERSION=2.2.2
  - secure: |-
      x85VA9iP+/ZkBaWiupbGeJBDM4MBTp98yBVnWIe+vbWMj07zmvrIfM6rsdgT
      hZ1uBgEzGfpZ/vnU8CQN6KYXmyG2Vy4j2RlOhHf7aChNh38VzCq+97gXmLCR
      2vwy+FPJQLEWklEbUPkbiaoGwn0TxIg2Q2LpEeSBuJy82aAXaFc=
  - secure: |-
      0N0Egg/il0d8zktIgVLrbkVnNaULIEhA7k/VufIiA1VqRtU2s63tvbEqkh8t
      7SvCgLvni0ewVVs8P2F9dGeG7HZ0WRJ3tcdZCcJG9IBk6xNcWAQveZ2goBKJ
      0Y0YksLljdKHv8mn02KX2tZxLVYjgzq09Dvn0+bGOzQU+TLbkPY=
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- play-${PLAY_VERSION}/play update
- travis/graylog2-server.sh
script: play-${PLAY_VERSION}/play test
after_script:
- kill `cat $HOME/graylog2-server/graylog2-travis-server.pid`
services:
  - mongodb
  - elasticsearch
addons:
  sauce_connect: true
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: |-
        g6Gpj2n1Bl6hIwWlywEkw8wRjpN2XuFsxFr9KQu/p7mRLYPdF3V5qQPVLBRd
        KvkjCIM7gZy2DTRNUooQPXdJB3npbnlbQn4jNWqA7/fp434Sw5sdfSUMawGr
        XvemLvn0KxQxCO9GfN3wfmYxEWJwXO36Q29BnRWWgMQOXpFFD8A=
